### ISSUE TITLE
Unable to install npm install electron-prebuilt-compile

### ISSUE THREAD

**Issue by jeremyblalock** [electron/electron-compile#102]
It looks like `electron-compile` is depending on a private NPM package, which has now been made public. On the [NPM page for "@paulcbetts/mime-types"](https://www.npmjs.com/package/@paulcbetts/mime-types) it recommends installing with:

```
npm install --save mime-types
```

But instead, we still have `@paulcbetts/mime-types` in the package.json.

When I try to install, this is what happens. Any help on how to fix this (aside from forking, modifying, and re-building the package)?

```
jblalock-0038:synack-desktop jeremy$ npm install --save-dev electron-prebuilt-compile
npm ERR! Darwin 15.2.0
npm ERR! argv "/Users/jeremy/.nvm/versions/node/v5.5.0/bin/node" "/Users/jeremy/.nvm/versions/node/v5.5.0/bin/npm" "install" "--save-dev" "electron-prebuilt-compile"
npm ERR! node v5.5.0
npm ERR! npm  v3.9.3
npm ERR! code E404

npm ERR! 404 no such package available : @paulcbetts/mime-types
npm ERR! 404 
npm ERR! 404  '@paulcbetts/mime-types' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'electron-compile'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jeremy/Documents/Synack/Code/experiments/synack-desktop/npm-debug.log
```

**Comment by paulcbetts** [comment]
Try upgrading npm? Something odd is going on. I was able to successfully install this after clearing my npm token

**Comment by jeremyblalock** [comment]
Realized this was caused by sinopia, which was intercepting all scoped packages. If others have this issue, the following can be added to `~/.nvmrc`:

```
@paulcbetts:registry=https://registry.npmjs.org/
```

**Comment by sators** [comment]
In case anyone comes here with the same Sinopia issue, @jeremyblalock's fix works for your `~/.npmrc` file. See: https://github.com/rlidwka/sinopia/issues/278

**Comment by tojocky** [comment]
Another issue I had was my npm login credential were expired. quick fixed by removing from ~/.npmrc
