### ISSUE TITLE
Uncaught Exception: TypeError: protocol.interceptBufferProtocol is not a function

### ISSUE THREAD

**Issue by johnathanhowell** [electron/electron-compile#107]
After upgrading to `electron-prebuilt-compile` 1.2.3, I get the following error on application launch:

```
Uncaught Exception:
TypeError: protocol.interceptBufferProtocol is not a function
    at initializeProtocolHook (/node_modules/electron-compile/lib/protocol-hook.js:115:12)
    at EventEmitter.protoify (/node_modules/electron-compile/lib/config-parser.js:317:9)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
```

1.2.2 does not produce this exception.

```
node --version
v6.2.1

npm --version
3.9.3
```

I'm on OSX, but users on Linux have reported this problem as well.

**Comment by kenan2002** [comment]
I think it's due to this bug https://github.com/electron/electron/pull/6195 that is fixed in the recent release.

**Comment by mnquintana** [comment]
Thanks @kenan2002! This was indeed a bug with Electron upstream – please update to the latest version, and it should work. Sorry for the trouble here!
