### ISSUE TITLE
Compile files that aren't included in the html

### ISSUE THREAD

**Issue by jamesbrown0** [electron/electron-compile#111]
Required/imported javascript is not compiled with Babel.

Import a module written with ES6 -> `Unexpected token export`

**Comment by mnquintana** [comment]
Unfortunately this is because of how Babel 6 works out of the box – you'll need to add a preset to use ES2015 module syntax: https://babeljs.io/#es2015

Just follow the setup instructions in that link, and you should be all set. Hope that helps, and sorry this turned out to be frustrating!

**Comment by mdings** [comment]
This doesn't work for me. Still receiving unexpected token error in importing.

Included bot the env and es2015 preset and tried configuring via .babelrc file and through package.json file. Both no luck.

**Comment by paulcbetts** [comment]
@mdings Can you share an example?

**Comment by mdings** [comment]
I think there was something else going on, got it working now!
