### ISSUE TITLE
Using text/css breaks ability of built app to serve CSS files

### ISSUE THREAD

**Issue by aendrew** [electron/electron-compile#123]
I've been fighting this for days now...

When using `electron-packager-compile` to build a project (At least, for Darwin; I haven't tried any other platforms), renderer CSS files served via:

`<link rel="stylesheet" type="text/css" href="index.css">`

...Get transferred as empty `text/plain` files in the built app and thus do not render. However, they transfer perfectly fine if running the app via `electron .`. 

Even more confusing, `text/less` files have no problem.

I've created an example repo depicting this here: https://github.com/aendrew/electron-compile-no-css-example

Note that if you run `npm electron`, you see the square as red — this is because both the LESS and CSS files are loading, but the latter is taking precedence. 

If you then run `npm start` (which does a build and opens the built app), you get a green square — this is because the LESS is loading, but the CSS is not. 

For now, one workaround is just to rename all CSS files to LESS and include as such.

**Comment by simongregory** [comment]
This is biting me too. Running under `electron .` just works. Building a production app with `electron-packager-compile` and running it surfaces the following failure in the response when loading css from `index.html`:

`<link rel="stylesheet" type="text/css" href="../styles/main.css"/>`

```javascript
Failed to compile /Users/simon/code/nip/releases/Downloads-darwin-x64/Downloads.app/Contents/Resources/app.asar/src/styles/main.css: Cannot read property 'get' of null
    TypeError: Cannot read property 'get' of null
        at CompilerHost._callee2$ (/Users/simon/code/nip/releases/Downloads-darwin-x64/Downloads.app/Contents/Resources/app.asar/node_modules/electron-compile/lib/compiler-host.js:311:32)
        at tryCatch (/Users/simon/code/nip/releases/Downloads-darwin-x64/Downloads.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:62:40)
        at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/simon/code/nip/releases/Downloads-darwin-x64/Downloads.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:336:22)
        at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/simon/code/nip/releases/Downloads-darwin-x64/Downloads.app/Contents/Resources/app.asar/node_modules/regenerator-runtime/runtime.js:95:21)
        at step (/Users/simon/code/nip/releases/Downloads-darwin-x64/Downloads.app/Contents/Resources/app.asar/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
        at /Users/simon/code/nip/releases/Downloads-darwin-x64/Downloads.app/Contents/Resources/app.asar/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:20
```

I did try using `passthrough` via `.compilerc`, ie:

```json
{
  "text/css": {
    "passthrough": true
  }
}
```

but that didn't solve things.

**Comment by simongregory** [comment]
I've discovered that the problem occurs when the `.cache` directory has been created, so running `electron .` can also generate the error above.

Using the [example repo](https://github.com/aendrew/electron-compile-no-css-example) @aendrew set up with versions of `electron@1.4.4`, `electron-compilers@4.0.3`, `electron-compile@3.3.6`,  `electron-packager@8.1.0` I get the same result - the failure happens in the built production app with the `.cache`.

**Comment by simongregory** [comment]
Looks like all we need is `text/css` [adding to the list of types](https://github.com/simongregory/electron-compilers/commit/0c8bcfbfd6a84afd2706715f05c441acac3a8e76) the passthrough compiler handles over in [electron-compilers](https://github.com/electron/electron-compilers).

**Comment by malept** [comment]
`electron-packager-compile` has been removed from this project due to its unreliability _(see: most of the issues marked electron-packager in this issue tracker)_. It's now recommended to use the [Electron Forge](https://github.com/electron-userland/electron-forge) project, because it uses both electron-compile and Electron Packager (among other community projects) to create distributable Electron apps.

Also, the text/css bug mentioned in this issue has been fixed.
