### ISSUE TITLE
What electron-packager changes are needed for better integration?

### ISSUE THREAD

**Issue by malept** [electron/electron-compile#127]
I was made aware of the electron-packager wrapper in this project via the #electron Slack channel. I took a quick look and noticed that you use the CLI instead of the API, the latter of which I would have probably recommended in this case. Regardless of the interface you choose, is there anything this project needs in terms of electron-packager features/bugfixes in order to provide a better integration? Perhaps some new hooks in the build process? Promises support?

**Comment by malept** [comment]
I think [Electron Forge](https://github.com/electron-userland/electron-forge) can replace the Electron Packager wrapper now (via `electron-forge package`).

**Comment by paulcbetts** [comment]
I am 100% for :fire:'ing the garbagetown wrapper we have and pushing people to electron-forge

**Comment by malept** [comment]
:skull: `electron-packager-compile`
