### ISSUE TITLE
Support of SCSS/SASS

### ISSUE THREAD

**Issue by TracyGJG** [electron/electron-compile#130]
Request: Any chance of getting the SCSS syntax from SASS supported please?

**Comment by RHNorskov** [comment]
I second this request

**Comment by davi-mbatista** [comment]
I third this request

**Comment by oknoorap** [comment]
+1 I fourth this request

**Comment by jerguslejko** [comment]
I fifth this request :cactus:

**Comment by paulcbetts** [comment]
See https://github.com/electron/electron-compile/issues/14#issuecomment-143580478, I want to support it too but node-sass is too much of a trash fire with Electron

**Comment by AidanNichol** [comment]
Would adding support for ```postcss``` be a away to support SCSS without using node-sass?
If it was a feasible solution it also give a way to support ccsnext etc.

**Comment by asdine** [comment]
I second this comment

**Comment by paulcbetts** [comment]
node-sass has been re-added in the latest version!
