### ISSUE TITLE
Typescript@2 module resolution fail

### ISSUE THREAD

**Issue by kwonoj** [electron/electron-compile#134]
I tried to hook one simple typescript with `electron-compile`, and was not able to figure out how to resolve modules, seeing error as below: 

`App threw an error during load
TypeError: Cannot read property 'resolvedModule' of undefined`

here's simple repo to repro issue -

https://github.com/kwonoj/electron_compile_ts_module

`npm run build`: manually invoke typescript compiler using tsconfg.json
`npm start`: electron main.ts

if `compilerc` skips to set `moduleResolution`, it tries to look local paths of typescript with given module name. 

Is there any configuration I miss to make this work?

**Comment by c4wrd** [comment]
I'm running into the same issue. I can resolve relative modules file, I cannot resolve anything from node_modules.

**Comment by kwonoj** [comment]
I'm closing this issue as recent compiler (at least) resolves issues resolving module.
