### ISSUE TITLE
auto refresh not working

### ISSUE THREAD

**Issue by jorfermo** [electron/electron-compile#135]
Hi

I'm just trying to start understanding how electron-compile works. I set up a minimalistic electron app based on electron-quick-start and everything works fine so far. 

The only problem I found is that when I modify any file it doesn't auto refresh. I have to kill the app and npm start it again. Is there anything I have to set up to get hot reloading?

Thanks!

**Comment by paulcbetts** [comment]
electron-compile doesn't do hot reloading yet, you should reload the page - you don't need to kill and restart it

**Comment by jorfermo** [comment]
Saving the files doesn't autorecompile so manually refreshing doesn't work either.

Do I have to do something to enable autorecompile?
