### ISSUE TITLE
Search path

### ISSUE THREAD

**Issue by AidanNichol** [electron/electron-compile#137]
I've moved my project over from using webpack and I really like this. I just wanted to check something.
Using webpack I can specify a search path to find my modules enabling me to import all modules relative to the `src` directory which is easier and more robust then having to specify the right number of `../` to get to the module from where ever I'm invoking it.
Is there a way to achieve this in `electron-compile`

**Comment by wasd171** [comment]
@AidanNichol check out `babel-plugin-root-import`, worked flawlessly for me!
I have a related issue. I want all imports starting with `~` to point at `src` folder, like `~/constants` => `src/constants`. I've configured Typescript to do so, by writing
```
"baseUrl": ".",
"paths": {
  "~/*": [
    "./src/*"
  ]
},
```
 in my `tsconfig.json` and in `text/typescript` section in `.compilerc`. It works fine with WebStorm, IDE gets the references to the needed file, but when I try to run it with `electron-forge` I get errors like `Cannot find module '~/constants'`. 

Perhaps a solution would be to run babel after typescript to use this handy plugin? How can I achieve that? Or is it a bug?

**Comment by wasd171** [comment]
UPD: looks like it's an intended decision of Typescript team. I have another question though. It is possible to achive nice module resolution with the following structure: 
```
node_modules
src
    index.html
    client.js
    main.js
    node_modules
        shared
            constants.ts
        app
        main
            server.ts
```
With this structure it is possible to write `import constants from 'shared/constants'` within any file in src folder. However it looks like `server.ts` is not compiled in this case. Is there any way to tell `electron-compile` to process files in inner `node_modules` folder? I am using `electron-forge`

**Comment by AidanNichol** [comment]
@wasd171 thanks for the heads up. I had stumbled across ```babel-plugin-module-resolver``` which solved the problem for me. The syntax is slightly different from that used the package you recommend (i.e. no prefix needed and multiple root folders allowed) and might solve your issue.

**Comment by wasd171** [comment]
@AidanNichol unfortunately I need a Typescript solution =(

**Comment by wasd171** [comment]
In case anyone stumbles across this issue again: check this link https://github.com/electron/electron-compile/issues/239
