### ISSUE TITLE
electron-packager-compile doesn't work on Windows

### ISSUE THREAD

**Issue by Lichtjaeger** [electron/electron-compile#138]
CMD output:

```
D:\pscheler\Documents\Projekte\Spectrometer>node_modules\.bin\electron-packager-compile

spawn D:\pscheler\Documents\Projekte\Spectrometer\node_modules\.bin\electron-packager ENOENT

D:\pscheler\Documents\Projekte\Spectrometer>node_modules\.bin\electron-packager
Usage: electron-packager <sourcedir> <appname> [options...]
...
```

**Comment by xaviergonz** [comment]
+1, though I just get to the ENOENT while doing

```
C:\WebProjects\elcomptest\electron-compile-universe>node_modules\.bin\electron-packager-compile .  --out=build

spawn C:\WebProjects\elcomptest\electron-compile-universe\node_modules\.bin\electron-packager ENOENT

C:\WebProjects\elcomptest\electron-compile-universe>node_modules\.bin\electron-packager-compile.cmd .  --out=build

spawn C:\WebProjects\elcomptest\electron-compile-universe\node_modules\.bin\electron-packager ENOENT
```
which is weird, since electron-packager and electron-packager.cmd are there
PS: no cygwin installed, using the standard windows command line

**Comment by xaviergonz** [comment]
Actually in the end I got it to work, but I had to install electron-packager as a global package, it won't work when it is installed as a local package and it is not part of the global packages. Also I have to manually specify the electron version with --version=??? or it won't build

**Comment by xaviergonz** [comment]
Also something that isn´t mention is that you need the electron-compiled as a runtime dependency when packaging even when using electron-prebuilt-compiled

**Comment by malept** [comment]
`electron-packager-compile` has been removed from this project, in favor of using the [Electron Forge](https://github.com/electron-userland/electron-forge) project, because the wrapper was unreliable and Forge uses both electron-compile and Electron Packager to create distributable Electron apps.
