### ISSUE TITLE
Issue installing: Invalid name: "@paulcbetts/mime-types"

### ISSUE THREAD

**Issue by aendrew** [electron/electron-compile#142]
I think this is probably more of a npm issue than with this library, but when I try to `npm install` on a colleague's computer, I'm getting a failure with error:

`Invalid name: "@paulcbetts/mime-types"`

Gist [here](https://gist.github.com/aendrew/1353e36df8665ff3b32d6cafaa074d92).

Any ideas?

**Comment by paulcbetts** [comment]
Your npm is too old to grok scoped packages, `npm install -g npm@latest`

**Comment by aendrew** [comment]
@paulcbetts Ah, apologies! I installed the latest stable of Node using `n stable` on the machine and it didn't fix it — I'm guessing it failed to update `npm` as well in the process. Will try that tomorrow; thanks!

**Comment by paulcbetts** [comment]
Oh wait, you _do_ have npm >= 3, what's the deal??

**Comment by aendrew** [comment]
@paulcbetts I solved it by `npm install -g npm && npm rebuild`, I think it was just a broken npm installation.
