### ISSUE TITLE
Very slow on big files

### ISSUE THREAD

**Issue by mifi** [electron/electron-compile#146]
I'm using this module and I have an Electron project with a <video> element which I set the src on to local video files. These files are naturally large and they are intercepted by the interceptBufferProtocol call, causing them to load super slow in the video player. As I understand it, interceptBufferProtocol reads all the files into memory before returning the content as a Buffer, even if it's a file that shouldn't be processed.
Would there be a simple way to passthrough some files without intercepting them at all? I can imagine if the files are really large (multiple GB) it will now crash the whole node process too.

**Comment by paulcbetts** [comment]
Ugh, I don't have any super great solutions here. You could create a custom protocol yourself, that would just redirect to local files via interceptFileProtocol
