### ISSUE TITLE
Difference between electron-compile and electron-prebuilt-compile

### ISSUE THREAD

**Issue by rllola** [electron/electron-compile#150]
Hello,

I am confused on what is the difference between the two modules ? I have never done electron app before. I saw the talk  "Making Electron Development Simpler, More Pleasant, and More Productive - GitHub Universe 2016" talk and wanted to give a try but he talks about electron-compile and his demo he is using electron-prebuilt-compile.

**Comment by MarshallOfSound** [comment]
@rllola `electron-prebuild-compile` is a wrapper around the standard `electron-prebuilt` with built in `electron-compile` hooks.

See https://github.com/electron/electron-compile#how-does-it-work-easiest-way

You can use the normal `electron-prebuilt` and set up the `electron-compile` hooks yourself if you want.  Check out:

https://github.com/electron/electron-compile#how-does-it-work-slightly-harder-way
