### ISSUE TITLE
Can I use pug/jade in place of html directly?

### ISSUE THREAD

**Issue by harryio** [electron/electron-compile#161]
so I've tried mainWindow.loadURL('file://path/to/index.pug') but it didn't render the html, instead displayed the contents as text

**Comment by paulcbetts** [comment]
This works but pug isn't set up yet, call it index.jade.

**Comment by harryio** [comment]
@paulcbetts can I use pug features?

**Comment by paulcbetts** [comment]
@harryio Not until I move to it

**Comment by reebr** [comment]
Any new information about it? 😕
