### ISSUE TITLE
electron-packager "wrapper" does not seem to work

### ISSUE THREAD

**Issue by inventor02** [electron/electron-compile#166]
Been trying to crack this for a while, whenever I compile the project with electron-packager, electron-compile does not process the files and use the compiled files, hence the javascript errors I get when the app hits "import" in the main file.

Package.json:
```
{
  "name": "staffportal-desktop",
  "packageName": "StaffPortal for Desktop",
  "version": "0.1.0",
  "description": "StaffPortal desktop application",
  "main": "./src/main.js",
  "repository": "https://github.com/inventor02/staffportal-desktop.git",
  "author": "George Peppard <george@inventor02.me> (http://inventor02.me)",
  "contributors": [
    "justinoboyle",
    "afroraydude"
  ],
  "license": "GPL-3.0",
  "scripts": {
    "start": "electron .",
    "dist:mac": "electron-packager . --asar --platform=darwin --arch=x64 --version=1.1.3 --app-bundle-id=me.inventor02.staffportal.desktop --app-category-type=public.app-category.utilities --overwrite"
  },
  "devDependencies": {
    "electron-packager": "^8.4.0",
    "electron-prebuilt-compile": "1.1.3"
  },
  "dependencies": {
    "react": "^15.4.1",
    "react-dom": "^15.4.1"
  }
}
```

.compilerc: default

**Comment by malept** [comment]
I suggest using [Electron Forge](https://github.com/electron-userland/electron-forge). It provides a better integration between electron-compile and Electron Packager.

**Comment by saschagehlich** [comment]
I'm having the same issues, even with electron forge. @paulcbetts What's the status on this one?

**Comment by malept** [comment]
A minimal example app repository with this behavior would greatly help in diagnosing this problem.

**Comment by paulcbetts** [comment]
100% you should use electron-forge, I'm going to deprecate electron-compile-packager soon, it's much much better than my crappy code!
