### ISSUE TITLE
Getting compilation errors for unsupported file type

### ISSUE THREAD

**Issue by benmarch** [electron/electron-compile#167]
First, thank you for this awesome tool! (It might be the only tool that just worked perfectly for me right out of the box).

When I use the `electron-packager-compile` cli tool, I am receiving some errors in the console like this:
```
Failed to compile file: path/to/some/xml_file.xml 
Compiling path/to/some/xml_file.xml resulted in a MIME type of application/xml, which we don't know how to handle
```
Looking through the compiler host code, it looks like MIME types that are completely unknown are ignored, but if it is known and there is no compiler for it then it throws this error.

Fortunately, this does not affect the resulting package, but I do have about 50 xml files in my repo and I get this error for each one.

I tried setting `"application/xml": { "passthrough": true }` but that resulted in a "cannot find compile for type application/xml" error.

Do you have any suggestions?

Thanks,
Ben

**Comment by paulcbetts** [comment]
@benmarch At least using electron-forge, I still see this error but the file is correctly showing up in the compile cache as passthrough, it should be fine to ignore this
