### ISSUE TITLE
Vue.js support?

### ISSUE THREAD

**Issue by harryio** [electron/electron-compile#168]
Can I use vuejs with electron compile, similar to react by specifying it in .compilerc?

**Comment by paulcbetts** [comment]
Yep, check out https://github.com/electron-userland/forge-examples, Vue 2.0 components are still not 100% but I'm definitely working on getting it going

**Comment by harryio** [comment]
@paulcbetts how about single file components? for ex. Home.vue, profile.vue etc

**Comment by brainscript** [comment]
@harryio They do work, the `<style>` tag (inside module files) somehow doesn't ...
@paulcbetts Is it supposed to work or just not (yet) implemented?

**Comment by harryio** [comment]
@brainscript do I need to add vue to .compilerc? I've npm installed it and tried the electron-forge example, but I'm getting `couldn't find the compiler for ./components/Home.vue'`

**Comment by paulcbetts** [comment]
@brainscript @harryio Stuff like this is the "Not working 100%" part :-/

**Comment by brainscript** [comment]
@harryio Sorry I didn't answer earlier, but no, it works out of the box ... at least for me using the [`electron-prebuilt-compile`package](https://www.npmjs.com/package/electron-prebuilt-compile).

**Comment by harryio** [comment]
@brainscript hmm I saw there's a vue compiler package installed with electron compile.. but still didn't work. Anyway, I'm gonna wait for some solid integration.

**Comment by harryio** [comment]
think this issue should be open till it gets resolved.

**Comment by brainscript** [comment]
@harryio I would rather create **an issue listing all of the missing/not working features** of the included libraries, stuff like the Vue.js component `<style>` or the Sass `@import`. Not only as a **todo list** to fix these issues in the future, but also **for those who want to know what features are not yet supported**. That issue could then be **linked on the `README.md`** together with something like _"Please not that some features of the included libraries are not yet supported, visit [this page](#) to learn more"_.

@paulcbetts What do you think?

**Comment by ahouse101** [comment]
Just a note for those finding this page now, to get `<style>` tags to work inside of single file Vue components, you can just add `vueify` as a dependency - it just works after that (or at least, it did for me inside of electron-forge).

**Comment by vintproykt** [comment]
This is actually quite confusing that I have to use both `electron-compile` and `vueify`, while `.compilerc` file doesn't introduce `vueify` and something makes it indistinguishable in the compile process.

**Comment by jam3sn** [comment]
How did you go about adding Vueify to your compilerc? I can't find any documentation to get single file components working with electron compile and electron forge.
