### ISSUE TITLE
Loading external file without precompiling in package

### ISSUE THREAD

**Issue by inyono** [electron/electron-compile#171]
I'm trying to load some external JavaScript that is not part of my electron app. But if I bundle (`electron-packager-compile`) my electron app, the webview containing the external JavaScript throws an error and the external file contains the following:
```
Failed to compile [external file]: Asked for [external file] but it was not precompiled!
```
Is there any way to specify that the file should not be precompiled but loaded as it is?

To clarify: it works in the unbundled version, i.e. when running `electron .`.

**Comment by paulcbetts** [comment]
You probably need to read it via `fs.readFile` then `eval` it.

**Comment by arekkas** [comment]
Shouldn't there be like a `data-react-compile-ignore` tag or something instead?

**Comment by arekkas** [comment]
Or maybe some sort of configuration that lets you white- or blacklist certain directories

**Comment by paulcbetts** [comment]
@arekkas It's possible, but I'm kinda not super excited to include that because electron-compile actually is providing you some security protection by refusing to load code that isn't shipped with your app. What scenarios are people actually wanting to do this?

**Comment by arekkas** [comment]
I see, we're building a static site app based on electron and want people to be able to include userland js.

**Comment by JakeDluhy** [comment]
I ran into this problem when trying to load a dynamically generated `.obj` file. Any thoughts as to how I could get around that problem? Using THREE.js,
```javascript
const loader = new THREE.OBJLoader();
loader.load('/url/to.obj', (object) => {
```
where `/url/to.obj` has just been dynamically generated from 3D scanning (not able to include it within the source code).

**Comment by hvhallmann** [comment]
yeah, I'm facing the same issue.
my program allow the user to select which videos he will see;
so, he puts the file name on a json file, and the program will load the video from current path.
video.setAttribute("src", arg);
It is working on development mode, but after package, I can't change any video.
I'll try with fs.readFile

**Comment by callodacity** [comment]
I have an application that generates a PDF file and opens it in a `BrowserWindow` - and `electron-compile` gives this error. I like the security feature `electron-compile` provides by not loading files, but at times I think it may be necessary... Any way around this issue for now?

**Comment by MarshallOfSound** [comment]
@callodacity Yes --> https://github.com/electron/electron-compile/pull/199

**Comment by rafortis** [comment]
@ghost try addind a bypass:
```
const addBypassChecker = require('electron-compile').addBypassChecker;
addBypassChecker((filePath) => {
  return /\.pdf/.test(filePath);
});
```
