### ISSUE TITLE
Issues with source maps

### ISSUE THREAD

**Issue by pronebird** [electron/electron-compile#172]
Hi,

I use `electron-compile` to bootstrap ES6 electron app.`init.js` is very trivial:

```js
require('electron-compile').init(__dirname, './app/main');
```

I am having issue enabling source maps so I wonder if it has something to do with how `electron-compile` works.

`.babelrc`

```json
{
  "presets": ["es2015", "stage-0", "react"],
  "plugins": ["transform-decorators-legacy", "transform-runtime"],
  "sourceMaps": true,
  "retainLines": true
}
```

**Comment by kwonoj** [comment]
I have made upstream changes in `electron-compilers` for groundwork to support separated source map other than inline in `electron-compile`, (https://github.com/electron/electron-compilers/pull/56) and trying to wire it with `electron-compile` for now.

In short, currently there is no way to emit sourcemap other than inlining.

**Comment by paulcbetts** [comment]
@pronebird Set source maps to inline instead, it should be the default unless you override it

**Comment by paulcbetts** [comment]
This should work for you, if you have a scenario where you really need source maps (there are a few), let us know what it is

**Comment by pronebird** [comment]
Yeah the only problem I experienced was that dev tools displayed files with inline source maps twice in Source tab (e.g. source mapped files were prefixed with [SM]). It seems that @kwonoj  nailed it already.
