### ISSUE TITLE
export default modules don't have a name - TypeScript

### ISSUE THREAD

**Issue by mbalex99** [electron/electron-compile#203]
```typescript
export class App extends React.Component<{}, {}> {
    render(){
        return (
            <div>
                <h1>Hey</h1>
            </div>
        )
    }
}
```

generates a name for the module. however, this doesn't

```typescript
export default class App extends React.Component<{}, {}> {
    render(){
        return (
            <div>
                <h1>Hey</h1>
            </div>
        )
    }
}
```

It results in this. It seems like it is parsing out `default` not `App` in this scenario

![image](https://cloud.githubusercontent.com/assets/2183729/23892851/8cbf242c-0859-11e7-983f-786cf2e34ac7.png)

**Comment by MarshallOfSound** [comment]
@mbalex99 This is correct and how `babel` works.

Default exports are exported as `default` on the `exports` object.  `import foo from 'bar'` will automatically import the default export for you though 👍

**Comment by mbalex99** [comment]
@MarshallOfSound  Unfortunately, this is happening on TypeScript/TSX. This generates a syntax error

**Comment by MarshallOfSound** [comment]
Hmm this might be more @paulcbetts territory then, I didn't have much to do with HMR on the typescript side of things 👍

**Comment by mbalex99** [comment]
I'm trying to find the place where this code is being generated. This is a really simple boilerplate project where this is occuring.

https://github.com/mbalex99/typescript-realm-electron/tree/react

I didn't enable any HMR or reloading techniques. Yet it seems to aggressively want to inject it in.

**Comment by MarshallOfSound** [comment]
@mbalex99 Looks to be coming from the typescript compiler for `electron-compilers`

https://github.com/electron/electron-compilers/commit/05384104bd0d4fcc64668235607dcf970c242ac9#diff-2571a26ad44f65862d33b2c9986b94c0R91

**Comment by mbalex99** [comment]
Jeez I was looking all over for this project for those characters. 😅 
Thanks I'll try to create a **PR** over there

**Comment by fasterthanlime** [comment]
https://github.com/electron/electron-compilers/pull/63 has been merged, so this can probably get closed!

**Comment by fasterthanlime** [comment]
this has now been fixed twice with this fix for the fix: https://github.com/electron/electron-compilers/pull/70 💯
