### ISSUE TITLE
How to create an alias for a NPM package?

### ISSUE THREAD

**Issue by ttraenkler** [electron/electron-compile#205]
For my project, I need to create an alias called `react-native` that resolves to `react-native-web`. This is usually done in the webpack configuration - how is this possible with electron-compile?

Thanks for your efforts put into electron-compile!

**Comment by MarshallOfSound** [comment]
This is not something that `electron-compile` should be doing.

You can do this in many ways in a node environment.

There is a module to do it for you: https://www.npmjs.com/package/module-alias

Or you can set it up as part of your babel config in your `.compilerc`: https://www.npmjs.com/package/babel-plugin-module-alias

**Comment by ttraenkler** [comment]
Thanks for the hint!

**Comment by karlitos** [comment]
Hi, I do not want to open extra ticket, but I think, that the [proposed solution ](https://github.com/electron-userland/electron-compile/issues/205#issuecomment-287328804) will not work in case I need to create an alias of __npm package A__ to __npm package B__ for the development environment.

Background: I am trying to get the [react-dom - hot-loader edition](https://github.com/hot-loader/react-dom) working, but I am still facing the [infamous warning message](https://github.com/gaearon/react-hot-loader/issues/1227).

Basically I need to alias __"react-dom"__ to __"@hot-loader/react-dom"__, so I updated my __.compilerc__ as follows:

```
{
  "env": {
    "development": {
      "application/javascript": {
        "presets": [
          ["env", { "targets": { "electron": "1.6.0" } }],
          "react"
        ],
        "plugins": ["transform-async-to-generator", "transform-es2015-classes", "react-hot-loader/babel",
        ["module-resolver", {
              "alias": {
                 "react-dom": "@hot-loader/react-dom"
              }
            }]
        ],
...
```
Sadly this did not help. Then I found [following issue ](https://github.com/tleunen/babel-plugin-module-resolver/issues/191) stating:

> Hi @siddharthkp, this would be possible (although not without problems) if you applied the transform to the files inside node_modules. Usually node_modules are ignored.

> Maybe you could manually add a "react" package to node_modules that would export preact-compat?

Might this be a reason, the __alias__ is not working as expected ? What can I do about this ?
