### ISSUE TITLE
I am getting an error while install electron(npm install electron or npm install -S electron)

### ISSUE THREAD

**Issue by VPageDevelopment** [electron/electron-compile#212]
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "electron"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ENOSELF

npm ERR! Refusing to install electron as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\codepanda\Desktop\electron\npm-debug.log

Thanks in Advance

**Comment by MarshallOfSound** [comment]
@VPageDevelopment `ENOSELF` is an error you get when you attempt to install a package a dependency of itself.  It looks like you are running `npm install electron` from inside an electron folder, potentially the electron project itself or a project called "electron".  You can't do this 👍
