### ISSUE TITLE
import of .less files in components

### ISSUE THREAD

**Issue by ChriD** [electron/electron-compile#225]
Hi, 
Is it possible to import a .less file within a component, so that the imported styles get unique id's by the compiler?
I have tried and i am getting an  error when importing a  .less file

`import styles from './test.less';`

```
 Uncaught SyntaxError: Unexpected token .
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.require.extensions.(anonymous function) [as .less]
```

test.less:
```
.test{
  background-color: blue;
}
```
importing the file in html via `<link>` works
I have to admit i am new to electron. It may be that i am making silly mistakes

**Comment by crunchex** [comment]
I'm interested in this too, but with just regular CSS.

I'm looking into https://www.npmjs.com/package/babel-plugin-css-modules-transform (which I acknowledge their disclaimer that it is experimental), but can't seem to get it to work.

**Comment by paulcbetts** [comment]
Node's module system only imports JS, importing CSS via an `import` statement is a weird Webpack hack. using the `link` tag is the way to do it (if you need to do it at runtime, create a link tag via `document.createElement`, then drop it in)
