### ISSUE TITLE
Can't start application when --debug is specified on the command line

### ISSUE THREAD

**Issue by Gum-Joe** [electron/electron-compile#238]
I've been recently attempting to debug my electron app (made with electron-forge) with `vscode`.  However, I have found that any attempt at using the `--debug` argument on the command line and in `vscode` (or any variation, for example: `--debug-brk=xxx`) causes the app to not run at all (no errors):
```powershell
PS D:\Users\Kishan\Documents\Projects\tara> ./node_modules/.bin/electron src/renderer/index.js --debug

PS D:\Users\Kishan\Documents\Projects\tara>
```
It is also an issue as the `--debug` switch is used to debug my app.

**I've tried:**

- Removing all imports from the entry file. No error was shown (not even an unhandled promise rejection).
- Compile code using babel. I got an error about `regeneratorRuntime` not being defined.
- Used `DEBUG=*:electron-compile`. I got no output.

You can find my code at [https://github.com/Gum-Joe/tara](https://github.com/Gum-Joe/tara) in the `src/` directory.

**Comment by MarshallOfSound** [comment]
This is an Electron issue that has been handled and will be fixed in the next release 👍 

https://github.com/electron/electron/issues/9434

**Comment by Gum-Joe** [comment]
Is there a way to install the beta to get it today? `npm i electron-compile@next` perhaps?

**Comment by MarshallOfSound** [comment]
@Gum-Joe This isn't an `electron-compile` issue, it's an `electron` issue, you will either have to downgrade your Electron version or wait for the next electron version 👍
