### ISSUE TITLE
Error running on Windows - cannot find module @paulcbetts/mime-types

### ISSUE THREAD

**Issue by mhagmajer** [electron/electron-compile#242]
Please see https://github.com/electron-userland/electron-forge/issues/244 . If you feel like this issue belongs more there, feel free to close this.

I'm cross posting because `@paulcbetts/mime-types` is a dependency of this package. The OSX build works fine, so my first guess was that Windows didn't resolve path with `@` correctly.

Can you please take a look?

**Comment by paulcbetts** [comment]
This hasn't changed any, let's track that over there
