### ISSUE TITLE
Consider adding react & jsx

### ISSUE THREAD

**Issue by stavlocker** [electron/electron-compile#252]
It'd be great if there was react & jsx compilation support right from the beginning (or it could be enabled in settings / downloaded in a different package that adds to electron-compile). It'd make developing apps with electron & electron-compile so much easier and better!

**Comment by MarshallOfSound** [comment]
@stavlocker You can already do this.  Either through `babel` and the `babel-preset-react` preset.  Or through `typescript` and enabling JSX transpilation

**Comment by MarshallOfSound** [comment]
Check out `electron-forge init --template=react`

**Comment by stavlocker** [comment]
@MarshallOfSound Thank you very much :)
