### ISSUE TITLE
Error when adding and importing a css file in the react template

### ISSUE THREAD

**Issue by AbdallahZ3** [electron/electron-compile#253]
an error occurs when adding a css file and importing it in a react component, and the error is "null code returned for "C:\Users\User\projects\project\src\components\App\App.css". Please raise an issue on 'electron-compile' with the contents of this file."

the error occurs even if the css file is empty and importing(i.e. just importing it)

**Comment by MarshallOfSound** [comment]
How are you importing the file?  Are you using less / scss or are you trying to import a css file into JS.

Importing CSS into a JS file is not supported, it is a webpack concept that does not translate into Electron development.

**Comment by AbdallahZ3** [comment]
you are right, I am importing the css file directly, I did not know that.
thanks

**Comment by MarshallOfSound** [comment]
If you want to use CSS / LESS / SCSS you should use `link` tags like normal HTML

```html
<link href="./path/to/file.less" rel="stylesheet" />
```
