### ISSUE TITLE
Correct way to use a preload script with electron-compile?

### ISSUE THREAD

**Issue by callodacity** [electron/electron-compile#259]
When creating a [`BrowserWindow`](https://electron.atom.io/docs/api/browser-window/#new-browserwindowoptions) one may enable a `webPreferences.preload` script. This script is loaded before the window is created and has various uses (see linked documentation).

Unfortunately since this preload script isn't caught by `electron-compile`, and doesn't end up being cached with the rest of the app's source. 

Is there a correct way to use a preload script with `electron-compile`?

**Comment by malept** [comment]
You'll have to do something like this:

https://github.com/electron-userland/electron-forge/wiki/Using-'preload'-scripts

_(That should really be in the electron-compile README.)_

**Comment by callodacity** [comment]
Ah, I must have missed that. Thanks 👍
