### ISSUE TITLE
lstat uses lowercase application path

### ISSUE THREAD

**Issue by whphhg** [electron/electron-compile#73]
Hey,

after upgrading from electron-compile@2.0.7 to @2.0.8 (or above) I start to experience the following issue "Uncaught Error: ENOENT: no such file or directory, lstat '/home/user/**a**pp' ... ATOM_SHELL_ASAR.js:1".

For some reason it's using a lowercased version of the path in lstat. If I create the lowercased folders with no content (/home/user/**a**pp/source/electron instead of original /home/user/**A**pp/source/electron) then it takes a second or two longer to load the html, but afterwards it runs fine serving content from the uppercase folder path.

I'm using npm 3.7.5 and node v5.7.0 on Linux arch 4.4.1-2-ARCH #1 SMP PREEMPT Wed Feb 3 13:12:33 UTC 2016 x86_64 GNU/Linux.

Other packages of interest:
- babel-core@6.6.0 
- babel-preset-es2015@6.6.0 
- electron-compilers@2.1.3 
- electron-prebuilt@0.36.9 

Any ideas what could be the issue?
Thanks in advance.

**Comment by paulcbetts** [comment]
Probably a regression from https://github.com/electronjs/electron-compile/pull/66, I'll look into it

**Comment by whphhg** [comment]
Great, thank you for taking the time! :mag:

**Comment by whphhg** [comment]
Any updates on this? As a workaround I've removed .toLowerCase() from return ret in src/sanitize-paths.js and lib/sanitize-paths.js.
