### ISSUE TITLE
How could I use this with electron-mocha?

### ISSUE THREAD

**Issue by rgbkrk** [electron/electron-compile#74]
We're writing our tests using [electron-mocha](https://github.com/jprichardson/electron-mocha) and running the main app with electron-compile. We're running into inconsistencies between the two as a result. Any suggestions for how we should either rely on electron-compile with electron-mocha or how to conduct tests that still use electron-compile?

/cc @jdfreder

**Comment by jdfreder** [comment]
Thanks for opening this @rgbkrk !

**Comment by paulcbetts** [comment]
I fixed a bug in electron-prebuilt-compile related to this, if you update to the latest version it should be fixed

**Comment by mnquintana** [comment]
@rgbkrk Just checking in – does this work with the latest version of `electron-prebuilt-compile` now?

**Comment by rgbkrk** [comment]
We're using babel to build on dev launch and before we package. We've also switched off of electron mocha for the sake of nyc to be able to instrument. No problems of this sort any more.

**Comment by paulcbetts** [comment]
Yep, see electron-spellchecker for an example
