### ISSUE TITLE
Babel error: Unknown options: base.name

### ISSUE THREAD

**Issue by rmp135** [electron/electron-compile#80]
After following the instructions and attempting to start the init file, I get the error `Unknown option: base.name` from the babel compiler. This prevents electron from starting the app.

I've removed pretty much everything that could be causing an issue on my side and it still occurs.

If you need any more info let me know.

As an aside, is there a way to completely disable the babel compiler? I don't wish to use it.

edit: Running the tests for electron-compile immediately fail with `Cannot find module 'babel-runtime/regenerator'`.

**Comment by mnquintana** [comment]
Do you have a `.babelrc` or `.compilerc` file? If so, can you post the contents of that / those file(s) here?

**Comment by rmp135** [comment]
I appreciate the reply but I don't have any of the files I was using when this issue occurred. I ended up using webpack as the compiler.

**Comment by DutchKevv** [comment]
+1 

also have this error, any fix for this?

**Comment by mnquintana** [comment]
@DutchKevv Do you have a .babelrc or .compilerc file? If so, can you post the contents of that / those file(s) here?

**Comment by DutchKevv** [comment]
I figured it out.. For me I just shouldn't have electron-prebuilt-compile installed, than it works fine
