### ISSUE TITLE
SVG files are not rendering correctly in packaged apps

### ISSUE THREAD

**Issue by reverentgeek** [electron/electron-compile#94]
After packaging an app using `electron-packager-compile`, `.svg` images that were previously working no longer render.

**Comment by maxkorp** [comment]
We're having this issue too. 
We've found 2 solutions, possibly a 3rd but thats untested

The hackiest: in the constructor of compillerHost, after line 68, we set the compiler type for `image/svg+xml` to passthrough. Works, but seems wrong somehow
```js
let compilersByMimeType = Object.assign({}, compilers);
compilersByMimeType['image/svg+xml'] = compilersByMimeType['text/plain'];
```

Less hacky, but less automatic too unfortunately. In config-parser, we change 
```js
  let opts = info.options[x];
    if (!(x in compilers)) {
      throw new Error(`Found compiler settings for missing compiler: ${x}`);
    }
```
to
```js
  let opts = info.options[x];
    if (!(x in compilers) && !opts.passthrough) {
      throw new Error(`Found compiler settings for missing compiler: ${x}`);
    }
```
and in our .compilerrc we add
```js
{
  "text/less": { passthrough: true }
}

That change still disallows custom config for non existant compilers, but allows passthrough compilers to be set, (which confirmed, using passthrough for SVG fixes the issue). 

Least hacky, but most (entirely really) theoretical, in the passthrough compiler, would setting 
`const inputMimeTypes = ['text/plain'];` to include `image/svg+xml` help it detect properly somehow?

**Comment by maxkorp** [comment]
@paulcbetts Anything i can help do to test this or otherwise move it along?

**Comment by paulcbetts** [comment]
How come https://github.com/electron/electron-compile/blob/master/src/compiler-host.js#L22 doesn't cause this to be passthrough?

**Comment by MarshallOfSound** [comment]
@paulcbetts Because of this line?

https://github.com/electron/electron-compile/blob/master/src/compiler-host.js#L538

The result mime type is also `'image/svg+xml'` so that if check fails?

**Comment by paulcbetts** [comment]
Hm, so that should only be true if we're working with a preprocessed HTML language like Jade

**Comment by maxkorp** [comment]
So does the inline html compiler pull any svg images in and directly inject them as markup then?

**Comment by paulcbetts** [comment]
@maxkorp It shouldn't, it only processes inline script / style tags

**Comment by maxkorp** [comment]
So is the desiret behavior then that if a type is in final form, and doesn't have a different matching compiler, it should be passthroughed?

**Comment by paulcbetts** [comment]
@maxkorp Ya, which is why this is Odd

**Comment by maxkorp** [comment]
Hrm, ok. I'll dig into it from that angle then.
