### ISSUE TITLE
Releasing with electron-builder

### ISSUE THREAD

**Issue by ManRueda** [electron/electron-compile#99]
I can't make it work, i don't know if is because `electron-builder` use another NPM name for `electron-packager`... But when i run my built app, throw an error about electron-compile not been found.

This is the right path? Keeping `electron-compile` in the built app?

**Comment by paulcbetts** [comment]
electron-builder has forked basically everything it depends on, you can talk to them about including electron-compile support

**Comment by mnquintana** [comment]
Closing this out, since it seems to be an upstream issue with `electron-builder` – let me know if I'm misunderstanding though!

**Comment by manikantag** [comment]
There is a issue for this https://github.com/electron-userland/electron-builder/issues/807. But no progress.

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/issues/807#issuecomment-288030921
